language: ruby
bundler_args: --without development
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq wbritish
   - cp config/database.travis.yml config/database.yml
script:
 - bundle exec rake db:create
 - bundle exec rake db:schema:load
 - bundle exec rake spec
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
matrix:
  allow_failures:
    - rvm: 2.0.0
branches:
 only:
   - master
