development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: tariff_development_pit
  single_threaded: true
  username: tariff
  password: tariff

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: tariff_test
  single_threaded: true
  username: tariff
  password: tariff
